// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using inventory.Data;

#nullable disable

namespace inventory.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20251212193951_identity")]
    partial class identity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("inventory.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("inventory.Models.Expense", b =>
                {
                    b.Property<string>("ExpenseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ExpenseId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("inventory.Models.ExpenseByCategory", b =>
                {
                    b.Property<string>("ExpenseByCategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseSummaryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ExpenseByCategoryId");

                    b.HasIndex("ExpenseSummaryId");

                    b.ToTable("ExpenseByCategories");
                });

            modelBuilder.Entity("inventory.Models.ExpenseSummary", b =>
                {
                    b.Property<string>("ExpenseSummaryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ExpenseSummaryId");

                    b.ToTable("ExpenseSummaries");
                });

            modelBuilder.Entity("inventory.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "d35623ee-bef6-42b2-8776-2f99f8bb4782",
                            Name = "Pinkscale Blazing Star",
                            Price = 456.04m,
                            Rating = 2.25m,
                            StockQuantity = 124834
                        },
                        new
                        {
                            ProductId = "8ac1ac77-7358-425e-be16-0bdde9f02e59",
                            Name = "Gila Milkvetch",
                            Price = 899.05m,
                            Rating = 3.56m,
                            StockQuantity = 799402
                        },
                        new
                        {
                            ProductId = "1afc136b-4d9f-4e8e-aace-8e1df908a404",
                            Name = "Rocky Mountain Zinnia",
                            Price = 264.37m,
                            Rating = 3.23m,
                            StockQuantity = 842192
                        },
                        new
                        {
                            ProductId = "af84cc12-4fea-4f58-aece-f2ce92ca9580",
                            Name = "Guadalupe Suncup",
                            Price = 555.93m,
                            Rating = 4.09m,
                            StockQuantity = 236333
                        },
                        new
                        {
                            ProductId = "86e3bb1c-2f5d-4774-98f3-4df7cddd0a0f",
                            Name = "Saline Phlox",
                            Price = 82.62m,
                            Rating = 4.8m,
                            StockQuantity = 601208
                        },
                        new
                        {
                            ProductId = "26b017c6-06d8-443f-9b4a-d6b1cee6f4c0",
                            Name = "Common Brighteyes",
                            Price = 435.44m,
                            Rating = 0.27m,
                            StockQuantity = 124068
                        },
                        new
                        {
                            ProductId = "440c9e80-6bf8-4eb3-b2d2-f81936d67de3",
                            Name = "Vermejo Phlox",
                            Price = 759.15m,
                            Rating = 2.46m,
                            StockQuantity = 234525
                        },
                        new
                        {
                            ProductId = "98255f4e-40a6-470f-89a5-0792729f8947",
                            Name = "Purple Marshlocks",
                            Price = 974.99m,
                            Rating = 4.82m,
                            StockQuantity = 739009
                        },
                        new
                        {
                            ProductId = "2a339fb2-f9f3-43bc-a85a-b217a0a38f12",
                            Name = "Hamatocaulis Moss",
                            Price = 639.9m,
                            Rating = 1.17m,
                            StockQuantity = 754285
                        },
                        new
                        {
                            ProductId = "8a8391b2-b4ac-4847-b652-66ffd8d65875",
                            Name = "Wax Myrtle",
                            Price = 62.95m,
                            Rating = 4.6m,
                            StockQuantity = 205240
                        },
                        new
                        {
                            ProductId = "be2157fb-7454-405e-9511-bf7ba81b7726",
                            Name = "Thladiantha",
                            Price = 699.0m,
                            Rating = 1.65m,
                            StockQuantity = 399124
                        },
                        new
                        {
                            ProductId = "fdf1ba3d-fa06-4ce5-90ff-d081c5d37176",
                            Name = "Common Tarweed",
                            Price = 899.61m,
                            Rating = 2.39m,
                            StockQuantity = 196884
                        },
                        new
                        {
                            ProductId = "afded6df-058f-477d-9878-e0e0b1d3dff3",
                            Name = "Smooth Phlox",
                            Price = 575.6m,
                            Rating = 4.38m,
                            StockQuantity = 673658
                        },
                        new
                        {
                            ProductId = "daa29167-82a7-474b-9687-b8b903e7ec69",
                            Name = "Lemmon's Beggarticks",
                            Price = 492.35m,
                            Rating = 1.07m,
                            StockQuantity = 205143
                        },
                        new
                        {
                            ProductId = "ccb83982-71f3-4497-bad8-7e64c6920dc6",
                            Name = "Globe Fimbry",
                            Price = 304.69m,
                            Rating = 2.62m,
                            StockQuantity = 388596
                        },
                        new
                        {
                            ProductId = "1936d406-e89e-40e4-bff7-1827532269d4",
                            Name = "Columbia Milkvetch",
                            Price = 845.15m,
                            Rating = 2.21m,
                            StockQuantity = 631658
                        },
                        new
                        {
                            ProductId = "c849a535-5f8b-47e3-889c-015693a644ac",
                            Name = "Girdlepod",
                            Price = 880.09m,
                            Rating = 1.49m,
                            StockQuantity = 65457
                        },
                        new
                        {
                            ProductId = "0c3e80ee-59b3-4fc4-b760-8b07acc2d3ae",
                            Name = "Lindley's Clerodendrum",
                            Price = 51.66m,
                            Rating = 1.53m,
                            StockQuantity = 263383
                        },
                        new
                        {
                            ProductId = "d8f5bee3-f3eb-4071-a124-6b857e0fd798",
                            Name = "Arizonia Dry Rock Moss",
                            Price = 746.88m,
                            Rating = 4.71m,
                            StockQuantity = 616812
                        },
                        new
                        {
                            ProductId = "8d15de86-0e4a-4414-9166-7a33610202d3",
                            Name = "Clamshell Orchid",
                            Price = 17.1m,
                            Rating = 0.79m,
                            StockQuantity = 604774
                        },
                        new
                        {
                            ProductId = "ea8fd0b9-c2d9-4d43-9c23-44cb99d079bb",
                            Name = "Fourleaf Mare's-tail",
                            Price = 905.04m,
                            Rating = 3.71m,
                            StockQuantity = 909107
                        },
                        new
                        {
                            ProductId = "25d01c80-bca1-4a00-b1d0-0fbd39ff9e89",
                            Name = "Simpson's Rosinweed",
                            Price = 184.41m,
                            Rating = 1.98m,
                            StockQuantity = 953695
                        },
                        new
                        {
                            ProductId = "1d6df6e3-b7ea-4507-9d66-87c6ee8ed5b9",
                            Name = "Lobelia",
                            Price = 163.6m,
                            Rating = 0.81m,
                            StockQuantity = 341530
                        },
                        new
                        {
                            ProductId = "000a8c23-5bca-436c-a216-4e747a94c511",
                            Name = "Yew Plum Pine",
                            Price = 196.27m,
                            Rating = 1.6m,
                            StockQuantity = 967173
                        },
                        new
                        {
                            ProductId = "c5b600dc-6bfb-492a-b335-c3cc8c707959",
                            Name = "Thimbleberry",
                            Price = 602.37m,
                            Rating = 0.13m,
                            StockQuantity = 162208
                        },
                        new
                        {
                            ProductId = "9d5fafbc-312b-47e8-ada1-283918f0c3b5",
                            Name = "Yellowturbans",
                            Price = 564.82m,
                            Rating = 4.74m,
                            StockQuantity = 33021
                        },
                        new
                        {
                            ProductId = "0114d5d4-ae48-46fa-b0ca-afe60eb88add",
                            Name = "Field Brome",
                            Price = 664.2m,
                            Rating = 0.13m,
                            StockQuantity = 363992
                        },
                        new
                        {
                            ProductId = "e5b0da8c-148d-4680-b262-8609fb8a10da",
                            Name = "Pentas",
                            Price = 685.1m,
                            Rating = 1.5m,
                            StockQuantity = 635092
                        },
                        new
                        {
                            ProductId = "2be5b024-2c96-4f29-912c-c6f36353f799",
                            Name = "Strigose Beard Lichen",
                            Price = 373.81m,
                            Rating = 1.06m,
                            StockQuantity = 35383
                        },
                        new
                        {
                            ProductId = "fcf2e432-62a3-4b6f-a34d-36e42a12272e",
                            Name = "Mad River Fleabane",
                            Price = 669.97m,
                            Rating = 1.34m,
                            StockQuantity = 880242
                        },
                        new
                        {
                            ProductId = "fc4c81e5-f1ac-40f5-8c6f-da3fbad5599d",
                            Name = "Chickenthief",
                            Price = 100.11m,
                            Rating = 0.49m,
                            StockQuantity = 896782
                        },
                        new
                        {
                            ProductId = "07238d8e-0037-4972-87ca-0df206ee3e42",
                            Name = "Palmleaf Poppymallow",
                            Price = 22.99m,
                            Rating = 3.42m,
                            StockQuantity = 635344
                        },
                        new
                        {
                            ProductId = "154b7860-23a2-4564-ad99-1745ab7122ef",
                            Name = "Guayanan Waterclover",
                            Price = 45.45m,
                            Rating = 0.34m,
                            StockQuantity = 456487
                        },
                        new
                        {
                            ProductId = "8d4bf814-65d4-4df4-84cc-68911d925fdf",
                            Name = "Emory's Acacia",
                            Price = 847.6m,
                            Rating = 1.79m,
                            StockQuantity = 638956
                        },
                        new
                        {
                            ProductId = "a52bf1bd-3d35-4cd2-849a-354e3952e2d2",
                            Name = "American Century Plant",
                            Price = 969.47m,
                            Rating = 3.66m,
                            StockQuantity = 248630
                        });
                });

            modelBuilder.Entity("inventory.Models.Purchase", b =>
                {
                    b.Property<string>("PurchaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseId");

                    b.HasIndex("ProductId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            PurchaseId = "5035f91e-4a29-411a-8779-17f6105675f1",
                            ProductId = "d35623ee-bef6-42b2-8776-2f99f8bb4782",
                            Quantity = 875,
                            Timestamp = new DateTime(2007, 9, 28, 15, 56, 51, 0, DateTimeKind.Local),
                            TotalCost = 7871.43m,
                            UnitCost = 4163.31m
                        },
                        new
                        {
                            PurchaseId = "85841cb5-2132-40f2-b923-9769ee3c199b",
                            ProductId = "8ac1ac77-7358-425e-be16-0bdde9f02e59",
                            Quantity = 471,
                            Timestamp = new DateTime(2015, 2, 1, 15, 4, 43, 0, DateTimeKind.Local),
                            TotalCost = 485.48m,
                            UnitCost = 5673.17m
                        },
                        new
                        {
                            PurchaseId = "de384851-f898-4495-99b8-73448bb470bf",
                            ProductId = "1afc136b-4d9f-4e8e-aace-8e1df908a404",
                            Quantity = 37,
                            Timestamp = new DateTime(2010, 10, 22, 21, 38, 20, 0, DateTimeKind.Local),
                            TotalCost = 4202.25m,
                            UnitCost = 3835.06m
                        },
                        new
                        {
                            PurchaseId = "e0b0486c-6396-42b7-9a84-e21bd3a88600",
                            ProductId = "af84cc12-4fea-4f58-aece-f2ce92ca9580",
                            Quantity = 201,
                            Timestamp = new DateTime(2020, 1, 25, 15, 30, 58, 0, DateTimeKind.Local),
                            TotalCost = 8028.29m,
                            UnitCost = 1822.27m
                        },
                        new
                        {
                            PurchaseId = "822e6025-e582-4e8c-b143-dc5ebad4c18c",
                            ProductId = "86e3bb1c-2f5d-4774-98f3-4df7cddd0a0f",
                            Quantity = 789,
                            Timestamp = new DateTime(2011, 12, 30, 14, 54, 41, 0, DateTimeKind.Local),
                            TotalCost = 5086.57m,
                            UnitCost = 9238.02m
                        },
                        new
                        {
                            PurchaseId = "dd6d3a14-92d5-40f4-9bf4-92fb4043882c",
                            ProductId = "26b017c6-06d8-443f-9b4a-d6b1cee6f4c0",
                            Quantity = 251,
                            Timestamp = new DateTime(2014, 2, 26, 3, 13, 31, 0, DateTimeKind.Local),
                            TotalCost = 9520.42m,
                            UnitCost = 2443.32m
                        },
                        new
                        {
                            PurchaseId = "434e5415-cb23-4170-b1e7-bc85737dc8c7",
                            ProductId = "440c9e80-6bf8-4eb3-b2d2-f81936d67de3",
                            Quantity = 418,
                            Timestamp = new DateTime(2001, 11, 19, 1, 49, 33, 0, DateTimeKind.Local),
                            TotalCost = 5394.89m,
                            UnitCost = 5085.79m
                        },
                        new
                        {
                            PurchaseId = "963a92ab-e092-4f3d-8b6a-5ab803550d78",
                            ProductId = "98255f4e-40a6-470f-89a5-0792729f8947",
                            Quantity = 926,
                            Timestamp = new DateTime(2020, 4, 27, 10, 53, 44, 0, DateTimeKind.Local),
                            TotalCost = 3526.35m,
                            UnitCost = 8626.52m
                        },
                        new
                        {
                            PurchaseId = "b4aebfdc-bce9-4e90-89fc-5098447d687a",
                            ProductId = "2a339fb2-f9f3-43bc-a85a-b217a0a38f12",
                            Quantity = 754,
                            Timestamp = new DateTime(2020, 2, 5, 15, 2, 55, 0, DateTimeKind.Local),
                            TotalCost = 8035.97m,
                            UnitCost = 9052.79m
                        },
                        new
                        {
                            PurchaseId = "de2ba6a2-c291-4a60-aad1-23d5749c5847",
                            ProductId = "8a8391b2-b4ac-4847-b652-66ffd8d65875",
                            Quantity = 365,
                            Timestamp = new DateTime(2020, 5, 7, 18, 41, 13, 0, DateTimeKind.Local),
                            TotalCost = 361.77m,
                            UnitCost = 1105.02m
                        },
                        new
                        {
                            PurchaseId = "78ea5f20-8fcc-4b6c-836f-e4b7a58d7479",
                            ProductId = "be2157fb-7454-405e-9511-bf7ba81b7726",
                            Quantity = 975,
                            Timestamp = new DateTime(2014, 8, 12, 19, 37, 41, 0, DateTimeKind.Local),
                            TotalCost = 9517.85m,
                            UnitCost = 4783.47m
                        },
                        new
                        {
                            PurchaseId = "61ba57e9-81fe-4d04-85b5-6aab219ced9d",
                            ProductId = "fdf1ba3d-fa06-4ce5-90ff-d081c5d37176",
                            Quantity = 286,
                            Timestamp = new DateTime(2008, 12, 7, 18, 18, 59, 0, DateTimeKind.Local),
                            TotalCost = 9006.07m,
                            UnitCost = 6910.82m
                        },
                        new
                        {
                            PurchaseId = "012d028b-4d6b-43bf-8d69-edf296133c9e",
                            ProductId = "afded6df-058f-477d-9878-e0e0b1d3dff3",
                            Quantity = 71,
                            Timestamp = new DateTime(2005, 12, 29, 12, 50, 55, 0, DateTimeKind.Local),
                            TotalCost = 5983.42m,
                            UnitCost = 4058.81m
                        },
                        new
                        {
                            PurchaseId = "8155b76c-3da2-4fb4-ba18-68bf8a2cec1b",
                            ProductId = "daa29167-82a7-474b-9687-b8b903e7ec69",
                            Quantity = 963,
                            Timestamp = new DateTime(2007, 8, 15, 21, 41, 49, 0, DateTimeKind.Local),
                            TotalCost = 4935.68m,
                            UnitCost = 2198.44m
                        },
                        new
                        {
                            PurchaseId = "4d449c76-ee8a-473e-8135-f74875a31964",
                            ProductId = "ccb83982-71f3-4497-bad8-7e64c6920dc6",
                            Quantity = 614,
                            Timestamp = new DateTime(2014, 12, 5, 8, 28, 48, 0, DateTimeKind.Local),
                            TotalCost = 6406.98m,
                            UnitCost = 6565.99m
                        },
                        new
                        {
                            PurchaseId = "115c6e6c-e6d0-418f-990e-1730f9e4b02e",
                            ProductId = "1936d406-e89e-40e4-bff7-1827532269d4",
                            Quantity = 193,
                            Timestamp = new DateTime(2003, 12, 17, 14, 52, 2, 0, DateTimeKind.Local),
                            TotalCost = 788.08m,
                            UnitCost = 2562.72m
                        });
                });

            modelBuilder.Entity("inventory.Models.PurchaseSummary", b =>
                {
                    b.Property<string>("PurchaseSummaryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPurchased")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseSummaryId");

                    b.ToTable("PurchaseSummaries");
                });

            modelBuilder.Entity("inventory.Models.Sale", b =>
                {
                    b.Property<string>("SaleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = "df8a03fa-c69c-4ffe-9e28-5febfb7a5ca9",
                            ProductId = "d35623ee-bef6-42b2-8776-2f99f8bb4782",
                            Quantity = 229,
                            Timestamp = new DateTime(2023, 11, 2, 6, 3, 0, 0, DateTimeKind.Local),
                            TotalAmount = 8012.55m,
                            UnitPrice = 221.1m
                        },
                        new
                        {
                            SaleId = "8d008094-bbb7-4b6f-a38c-0e2a9905322d",
                            ProductId = "8ac1ac77-7358-425e-be16-0bdde9f02e59",
                            Quantity = 241,
                            Timestamp = new DateTime(2023, 8, 17, 22, 53, 36, 0, DateTimeKind.Local),
                            TotalAmount = 5661.25m,
                            UnitPrice = 414.68m
                        },
                        new
                        {
                            SaleId = "4fca2797-3e88-40c5-88d3-fd4df8744958",
                            ProductId = "1afc136b-4d9f-4e8e-aace-8e1df908a404",
                            Quantity = 699,
                            Timestamp = new DateTime(2023, 11, 21, 17, 3, 18, 0, DateTimeKind.Local),
                            TotalAmount = 4708.54m,
                            UnitPrice = 550.22m
                        },
                        new
                        {
                            SaleId = "ae6a3d09-fdf8-407b-9e55-07a347c87efa",
                            ProductId = "af84cc12-4fea-4f58-aece-f2ce92ca9580",
                            Quantity = 182,
                            Timestamp = new DateTime(2023, 5, 17, 23, 20, 3, 0, DateTimeKind.Local),
                            TotalAmount = 9419.4m,
                            UnitPrice = 113.69m
                        },
                        new
                        {
                            SaleId = "f4dced2f-4446-450b-9778-fd32fe4dc583",
                            ProductId = "86e3bb1c-2f5d-4774-98f3-4df7cddd0a0f",
                            Quantity = 863,
                            Timestamp = new DateTime(2023, 6, 14, 18, 17, 34, 0, DateTimeKind.Local),
                            TotalAmount = 8942.2m,
                            UnitPrice = 214.01m
                        },
                        new
                        {
                            SaleId = "b9c0856c-d10f-47a1-bf05-2f2c400aff69",
                            ProductId = "26b017c6-06d8-443f-9b4a-d6b1cee6f4c0",
                            Quantity = 985,
                            Timestamp = new DateTime(2023, 10, 27, 20, 59, 51, 0, DateTimeKind.Local),
                            TotalAmount = 1790.08m,
                            UnitPrice = 506.74m
                        },
                        new
                        {
                            SaleId = "4411942c-1d3e-42b1-89bd-a692c43185b4",
                            ProductId = "440c9e80-6bf8-4eb3-b2d2-f81936d67de3",
                            Quantity = 607,
                            Timestamp = new DateTime(2023, 6, 17, 22, 16, 31, 0, DateTimeKind.Local),
                            TotalAmount = 3293.73m,
                            UnitPrice = 100.77m
                        },
                        new
                        {
                            SaleId = "85460f0a-83d5-45b5-8db0-42506e0c5739",
                            ProductId = "98255f4e-40a6-470f-89a5-0792729f8947",
                            Quantity = 93,
                            Timestamp = new DateTime(2024, 1, 12, 18, 37, 28, 0, DateTimeKind.Local),
                            TotalAmount = 5531.81m,
                            UnitPrice = 310.09m
                        },
                        new
                        {
                            SaleId = "1d9c4316-ed1a-49c5-a9ed-71a9fc8aff1c",
                            ProductId = "2a339fb2-f9f3-43bc-a85a-b217a0a38f12",
                            Quantity = 482,
                            Timestamp = new DateTime(2023, 11, 8, 20, 16, 52, 0, DateTimeKind.Local),
                            TotalAmount = 894.41m,
                            UnitPrice = 83.62m
                        },
                        new
                        {
                            SaleId = "94a6ad98-8efe-4aef-bf19-742a542cf790",
                            ProductId = "8a8391b2-b4ac-4847-b652-66ffd8d65875",
                            Quantity = 285,
                            Timestamp = new DateTime(2023, 12, 22, 0, 49, 11, 0, DateTimeKind.Local),
                            TotalAmount = 3738.87m,
                            UnitPrice = 76.09m
                        },
                        new
                        {
                            SaleId = "cff83ef4-6b2c-4ad4-b550-929e0eb3fa93",
                            ProductId = "be2157fb-7454-405e-9511-bf7ba81b7726",
                            Quantity = 219,
                            Timestamp = new DateTime(2023, 11, 21, 17, 3, 43, 0, DateTimeKind.Local),
                            TotalAmount = 8773.57m,
                            UnitPrice = 606.43m
                        },
                        new
                        {
                            SaleId = "bc6fbde5-325d-4918-b8d9-36d8a7be769f",
                            ProductId = "fdf1ba3d-fa06-4ce5-90ff-d081c5d37176",
                            Quantity = 286,
                            Timestamp = new DateTime(2024, 3, 1, 19, 35, 27, 0, DateTimeKind.Local),
                            TotalAmount = 3328.18m,
                            UnitPrice = 246.58m
                        },
                        new
                        {
                            SaleId = "022fe7a7-3938-4f41-9f56-f9e0a797f00f",
                            ProductId = "afded6df-058f-477d-9878-e0e0b1d3dff3",
                            Quantity = 107,
                            Timestamp = new DateTime(2023, 6, 27, 15, 9, 45, 0, DateTimeKind.Local),
                            TotalAmount = 3915.37m,
                            UnitPrice = 891.26m
                        },
                        new
                        {
                            SaleId = "e6fc26ef-50e8-4983-a7e0-f2cbf32d32ef",
                            ProductId = "daa29167-82a7-474b-9687-b8b903e7ec69",
                            Quantity = 195,
                            Timestamp = new DateTime(2023, 7, 6, 5, 50, 19, 0, DateTimeKind.Local),
                            TotalAmount = 725.11m,
                            UnitPrice = 809.59m
                        },
                        new
                        {
                            SaleId = "5ab2a0f1-2248-4804-9bf0-219d8a30b076",
                            ProductId = "ccb83982-71f3-4497-bad8-7e64c6920dc6",
                            Quantity = 339,
                            Timestamp = new DateTime(2023, 3, 18, 3, 14, 42, 0, DateTimeKind.Local),
                            TotalAmount = 3694.96m,
                            UnitPrice = 662.74m
                        },
                        new
                        {
                            SaleId = "a3659c0d-ccc6-4903-b035-6f13e7778253",
                            ProductId = "1936d406-e89e-40e4-bff7-1827532269d4",
                            Quantity = 71,
                            Timestamp = new DateTime(2023, 11, 5, 2, 17, 48, 0, DateTimeKind.Local),
                            TotalAmount = 2535.36m,
                            UnitPrice = 529.95m
                        });
                });

            modelBuilder.Entity("inventory.Models.SalesSummary", b =>
                {
                    b.Property<string>("SalesSummaryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SalesSummaryId");

                    b.ToTable("SalesSummaries");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("inventory.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("inventory.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inventory.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("inventory.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("inventory.Models.ExpenseByCategory", b =>
                {
                    b.HasOne("inventory.Models.ExpenseSummary", "ExpenseSummary")
                        .WithMany("ExpenseByCategories")
                        .HasForeignKey("ExpenseSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseSummary");
                });

            modelBuilder.Entity("inventory.Models.Purchase", b =>
                {
                    b.HasOne("inventory.Models.Product", "Product")
                        .WithMany("Purchases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("inventory.Models.Sale", b =>
                {
                    b.HasOne("inventory.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("inventory.Models.ExpenseSummary", b =>
                {
                    b.Navigation("ExpenseByCategories");
                });

            modelBuilder.Entity("inventory.Models.Product", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
